pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: 'true'
  branches:
    include: [ master, develop ]
  paths:
    include:
    - src/Yobo.Server/*
    - src/Yobo.Shared/*
    - src/Yobo.Core/*
    - src/Yobo.Libraries/*

steps:
  - task: DotNetCoreInstaller@2
    displayName: Installing .net core sdk
    inputs:
      version: '3.1.300'
      packageType: sdk

  - script: dotnet tool restore
    displayName: 'dotnet tool restore'

  - script: dotnet fake build -t publishServer
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish App Artifacts'
    inputs:
      pathtoPublish: './deploy/server'
      artifactName: 'server'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Migrations Artifacts'
    inputs:
      pathtoPublish: './deploy/dbMigrations'
      artifactName: 'yobo-dbMigrations'    