# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: fake build -t publish
  displayName: 'Publish'

# Publish Pipeline Artifact
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'yobo-app'
    targetPath: ./deploy
