pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include: [ master, develop ]

steps:
- script: fake build -t publish
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: './deploy'
    artifactName: 'yobo-app'