# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: fake build -t publish
  displayName: 'Publish'
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: ./deploy
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/yobo-app.$(Build.BuildId).zip' 
    replaceExistingArchive: true 

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/yobo-app.$(Build.BuildId).zip'
    #artifactName: 'drop' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
