pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include: [ master, develop ]

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .net core sdk 2.2.100
  inputs:
    version: '2.2.100'
    packageType: sdk

- script: fake build -t publish
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: './deploy'
    artifactName: 'yobo-app'