pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include: [ master, develop ]

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .net core sdk 2.2.100
  inputs:
    version: '2.2.100'
    packageType: sdk

- script: dotnet tool install --tool-path . paket
  displayName: 'Install Paket'

- script: dotnet tool install --tool-path . fake-cli
  displayName: 'Install FAKE'

- script: dotnet run -p tools\EventStoreBackup\ "$(keysTable)" "$(accountName)" "$(authKey)"
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Backup Artifacts'
  inputs:
    pathtoPublish: './backup'
    artifactName: 'yobo-app-backup'