name: Database Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.300

      - name: Install SQL Dumper
        run: dotnet tool install --global SQLDumper.Tool 

      - name: Dump database
        run: sqldump "${{ secrets.DB_CONNECTIONSTRING }}" "backup.sql"

      - name: Backup dump
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: backup.sql
          destination_repo: ${{ secrets.BACKUP_REPO }}
          destination_folder: .
          user_email: ${{ secrets.BACKUP_REPO_EMAIL }}
          user_name: 'Dzoukr'
